export interface Voucher {
  id: string; // UUID
  title: string; // Maximum 255 characters
  description: string;
  image_url?: string | null; // Nullable text
  start_date: string; // ISO 8601 format (timestamp with time zone)
  end_date: string; // ISO 8601 format (timestamp with time zone)
  is_active: boolean; // Default is true
  created_at: string; // ISO 8601 format (timestamp with time zone)
  updated_at: string; // ISO 8601 format (timestamp with time zone)
  prefix: string; // Default substring(md5(random()), 1, 4), unique constraint
  max_claim: number; // Default 1, bigint
}

export interface VoucherClaim {
  id: string; // UUID, generated automatically
  user_id: string; // UUID, references auth.users(id)
  voucher_id: string; // UUID, references vouchers(id)
  claimed_at: string; // ISO 8601 format (timestamp with time zone), defaults to current timestamp
  is_redeemed: boolean; // Defaults to false
  redeemed_at?: string | null; // Nullable ISO 8601 format (timestamp with time zone)
  voucher_code: string; // Text, not null, generated by trigger
}
// Enum for approle
export type AppRole = "customer" | "admin" | "staff";

export interface Profile {
  created_at: string; // ISO 8601 format (timestamp with time zone), default to now()
  fullname?: string | null; // Nullable text
  whatsapp?: string | null; // Nullable text, must match '^08[0-9]{9,11}$'
  id: string; // UUID, references auth.users(id)
  email_address: string; // Unique email address
  approle: AppRole; // Enum type app_role, default is 'customer'
}
